### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#103]
https://ci.ukstats.dev/job/GSS_data/job/dd-cms/job/core-cms/job/main/5/testReport/ shows a couple of our tests are failing and `yarn test` suggests updating the snapshot files.

**Comment by nosnickid** [comment]
Upgraded to jest 26 to fix the "_jsxFileName" problem.

Use "jest" directly in the "test" script - it was "razzle test" before, which was causing it to load the base plone jest config rather than our overrides.

Updated assorted snapshots and mocked the imports as jest will see them to simplify components used by the components we are testing.
