### ISSUE TITLE
Plan for how to switch beta2 to live

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#560]
Do ahead:
- [x] Understand if/how we can pull the existing climate-change.data.gov.uk cert, or decide to follow existing documentation and create a new cert
- [x] Create certs2.yaml (or similar) to contain the climate-change.data.gov.uk cert and add it to nginx ahead
- [x] (quick, could be done any time up to launch) Update redirect URL on OAuth configuration to the climate-change.data.gov.uk domain
- [x] @JohnLewisUR  to generate new Hotjar code, then devs to apply to the deployment (maybe the day before/shortly ahead)
- [x] Take manual backups of both CCv1 and CCv2 before changes

On the day:
- [x] Update the nginx proxy configuration to reverse proxy climate-change.data.gov.uk within the cluster, also turn off basic auth on that domain
- [x] Update the A record for the climate-change.data.gov.uk DNS entry to point to the ccv2 k8s cluster
- [x] Configure OAuth

 
@peterfrenchons please can you add the start/end comms we should expect? Are we waiting to be told to go from someone day of? Who do we tell once it's up?

**Comment by eldeal** [comment]
At this point we're actually saying we need to:
- deploy most up to date CCv2 code to the k8s cluster, which currently is fronted by beta2....
- Update load balancer so beta... directs to the cluster instead of beta2...
- Update certificates to beta... is secured on the correct load balancer
- Remove the basic auth from the cluster

This would make beta.cli.... (CCv2) a publicly available service, backed my our k8s platform.
At the Climate Teams discretion, we can add some pointer from climate-change.data... to say 'hey look at our new Beta service' (CCv2) and link to beta... 

Down the road we'll also look to move (once more assured) the k8s platform from beta... to climate-change.data in place of v1. Very far down the road, there will be a separate conversation about moving from the 'Beta' lifecycle phase to 'Live' across the service, but that is not on the cards this year.

**Comment by charlesons** [comment]
Provide handover documentation
Update the failsafe login credentials

**Comment by eldeal** [comment]
Dress Rehearsal:
- Certificate / DNS propogation took ~15-20 mins
- Created the new OAuth Client (Charles has the keys)
- Noticed a few pages/charts hand't been published yet (dashboard tiles on landing page), so we published them
- Change the DNS A record back to put old climate change back

Morning of we need to:
- once the climate team are done making any changes they might want, early morning we can change the OAuth credentials in Plone to the new Client ID (Charles!)
- At the appointed moment, change the DNS A records

**Comment by charlesons** [comment]
Extracted the decommissioning of CC Beta and CC v1 tasks into https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/gss-cogs/dd-cms/719
