### ISSUE TITLE
Spike: integrate existing CB into Volto

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#63]

**Comment by nosnickid** [comment]
Integrating this into a volto addon.

Having some trouble with govuk-react-jsx again - the import problems - so I'm going to fork it and try to package it 'correctly' so that the server side rendering works.

**Comment by nosnickid** [comment]
Spent all day faffing with this. Distributing assets in node packages is a free for all; there's no canonical way to handle it. https://github.com/webpack/webpack/issues/7353 goes into this in some depth.

We have another fiddly element; we're trying to import() an image from a peer dependency. It doesn't make any sense to include the peer dependency image in the built `govuk-react-jsx` anyway.

I spent the day messing with alternative ways of packaging `govuk-react-jsx`, as a ES module instead of JS, but that was a bit of a rabbit hole that couldn't fix it.

To start from the top. 

- We're using `govuk-react-jsx` which has an `import` statement for an image contained in `govuk-frontend`.
- If we use the packaged `govuk-react-jsx` available in npm, the ES6 source (using `import`) has been transpiled by babel into CommonJS (`require()`)
- Because it is in `node_modules` in our project, the razzle `webpack` loaders assume it can be loaded directly and let the node cjs require() happen directly
- Ultimately this means node tries to parse the PNG as a JS file, and obviously fails.

I'm going to try one more thing, which is to add a webpack loader that will actually load the `govuk-react-jsx` module from `node_modules`. That should intercept the require() on the image.

**Comment by nosnickid** [comment]
Another long day of fighting razzle on this.

Razzles SSR is done in a `express` webserver in the `server.jsx` file in volto.  Because it's `jsx`, that implies that webpack is intercepting the file load, passing it through babel to transpile jsx -> `React.createElement` calls, and then letting Node load the transpiled file.

If that is the case, I can't currently explain why, when it eventually loads `govuk-react-jsx/.../Header.js`, the `require()` statement in that file for the PNG isn't also intercepted by webpack, and handle by its file-loader.

**Comment by nosnickid** [comment]
Getting somewhere now. `govuk-react-jsx` is being treat as an `external` by webpack, which mean it gets loaded directly.

Hacking the `externals` to whitelist (ie, to treat it as not-external...)  `govuk-react-jsx` fixes it.

So now I just need to patch the webpack config in the right way.

**Comment by dmsltd** [comment]
@nosnickid, good one on the progress. 

This thread looks like it could be relevant:

https://github.com/plotly/react-plotly.js/issues/21

**Comment by charlesons** [comment]
Basically looks like the fundamental issue is that plotly.js doesn't support SSR

_"A point to note here, as of the time of writing this blog, ploty.js is a client-side rendering library and doesn't yet support server side rendering."_

source: https://dev.to/dheerajmurali/building-a-responsive-chart-in-react-with-plotly-js-4on8

**Comment by nosnickid** [comment]
Ah ha. Ok, so I think the next step is to make chart builder detect when
it's running server side (`__SERVER__` constant I think) and conditionally
load react-plotly, by using require() rather than import.

**Comment by charlesons** [comment]
Yes sounds right.

Another potential solution is to use the webpack feature for separate imports for server and browser suggested by @nhimhobao:

https://github.com/jaredpalmer/razzle/issues/606

**Comment by nosnickid** [comment]
Hrm, with react plotly being used so deeply in the component hierarchy it
might be fiddly to use the webpack feature in chart builder.

**Comment by charlesons** [comment]
Loading the `react-plotly.js` import using `React.lazy` in `ChartPreview.tsx ` seems to have resolved the issue - more testing required to be sure.

`const Plot = React.lazy(() => import("react-plotly.js"));`

Source: https://reactjs.org/docs/code-splitting.html

Perhaps there's a more optimal solution using `@loadable/component` which is in fact already included within the volto project. 

https://medium.com/1mgofficial/code-splitting-ssr-lazy-loading-react-components-a-deeper-understanding-part-1-7d714196706

**Comment by nosnickid** [comment]
Next steps

- [ ] Fix flexbox problem
- [ ] Make the various static texts editable in the volto style
- [ ] Use plone file source for CSV

**Comment by nosnickid** [comment]
The latest changes to this now let you select a CSV file uploaded as a regular 'File' content in plone.

It fetches the CSV from plone and does all the same parsing it does when using the browser file selection.

**Comment by nosnickid** [comment]
This is now merged into main via #126
