### ISSUE TITLE
CMS Search - No results found shows even when there are results

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#728]

**Comment by eldeal** [comment]
This might actually be a feature more than a bug - I can find results for 'emissions' because it's a page title, but I get nothing for 'trees' or 'rivers' even though that's in the content of pages. So a search that requires you know a block title might not be too useful.

@edd-harvey do you want us to improve search to consider content in the short term, or are we leaving that sort of search feature for the big re-look coming down the road?

**Comment by edd-harvey** [comment]
Let's pick this up in refinement
